/**
 * This class is generated by jOOQ
 */
package com.dtc.test.qsm.server.dao.orm.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contacts implements Serializable {

    private static final long serialVersionUID = 283164587;

    private String name;
    private String email;
    private String phone;

    public Contacts() {}

    public Contacts(Contacts value) {
        this.name = value.name;
        this.email = value.email;
        this.phone = value.phone;
    }

    public Contacts(
        String name,
        String email,
        String phone
    ) {
        this.name = name;
        this.email = email;
        this.phone = phone;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Contacts (");

        sb.append(name);
        sb.append(", ").append(email);
        sb.append(", ").append(phone);

        sb.append(")");
        return sb.toString();
    }
}
